# Generated by Django 2.2.7 on 2020-11-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_manager_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
